version: "3.8"
services:
  redis:
    image: redis:6.0.6
    volumes:
      - ./docker-volume/:/data
    expose:
      - 6379
    ports:
     - 6379:6379
    restart: always
    networks:
      - service-network

  service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      REDIS_ADDRESS: redis:6379
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - service-network

networks:
  service-network:
    name: service-network
